import logging
import warnings
from fireducks_worker import FireducksWorker
from typing import Any

logger = logging.getLogger(__name__)

global_vars = None

class FireducksAppWorker(FireducksWorker):
    def start(self) -> Any: ...
    def work_init(self) -> Any: ...
    def pool_init(self, *args: Any, **kwargs: Any) -> Any: ...
    def work_pool(self, *args: Any, **kwargs: Any) -> Any: ...
    def work_done(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop(self) -> Any: ...
