from __future__ import annotations

USER_ENV_DEFAULT_COMMENT_LINES: tuple[str, ...] = (
    '# AGI_PYTHON_VERSION="3.14"',
    '# 127.0.0.1_PYTHON_VERSION="3.14"',
    '# AGI_PYTHON_FREE_THREADED="1"',
    '# IS_SOURCE_ENV="1"',
    '# IS_WORKER_ENV="0"',
    '# OPENAI_API_KEY=""',
    '# OPENAI_BASE_URL=""',
    '# OPENAI_MODEL="gpt-5.4-mini"',
    '# AGILAB_DEFAULT_OPENAI_MODEL="gpt-5.4-mini"',
    '# AZURE_OPENAI_API_KEY=""',
    '# AZURE_OPENAI_ENDPOINT=""',
    '# AZURE_OPENAI_API_VERSION=""',
    '# AZURE_OPENAI_DEPLOYMENT=""',
    '# MISTRAL_API_KEY=""',
    '# MISTRAL_BASE_URL="https://api.mistral.ai/v1"',
    '# MISTRAL_MODEL="mistral-medium-3.5"',
    '# MISTRAL_REASONING_EFFORT="high"',
    '# MISTRAL_TEMPERATURE=""',
    '# MISTRAL_MAX_TOKENS=""',
    '# MISTRAL_TIMEOUT="120"',
    '# AGILAB_LLM_BASE_URL="http://127.0.0.1:8000/v1"',
    '# AGILAB_LLM_MODEL="Qwen/Qwen2.5-Coder-7B-Instruct"',
    '# AGILAB_LLM_API_KEY="EMPTY"',
    '# AGILAB_LLM_TEMPERATURE="0.1"',
    '# AGILAB_LLM_MAX_TOKENS=""',
    '# AGILAB_LLM_TIMEOUT="120"',
    '# LAB_LLM_PROVIDER=""',
    '# UOAIC_MODE=""',
    '# UOAIC_OLLAMA_ENDPOINT="http://127.0.0.1:11434"',
    '# UOAIC_MODEL=""',
    '# APP_DEFAULT="minimal_app_project"',
    '# APPS_PATH="/path/to/agilab/src/agilab/apps"',
    '# APPS_REPOSITORY="/path/to/your-apps-repository"',
    '# AGILAB_DEV_APPS_REPOSITORY=""',
    '# AGILAB_ALLOW_FLOATING_APPS_REPOSITORY="0"',
    '# MLFLOW_TRACKING_DIR=".mlflow"',
    '# AGI_CLUSTER_SHARE="clustershare/<user>"',
    '# AGI_LOCAL_SHARE="localshare/<user>"',
    '# AGI_LOG_DIR="log"',
    '# AGI_EXPORT_DIR="export"',
    '# AGILAB_LOG_ROOT="log"',
    # AGILAB_EXPORT_DIR is a deprecated alias of AGI_EXPORT_DIR (the name the
    # runtime actually reads); kept commented for one release. Do not present it
    # as an independent/equivalent setting.
    '# AGILAB_EXPORT_DIR="export"',
    '# AGILAB_WORKFLOW_DATA_ROOT=""',
    '# CLUSTER_CREDENTIALS="agi:2633"',
    '# AGI_CLUSTER_ENABLED="0"',
    '# AGI_WORKERS=""',
    '# AGI_SCHEDULER_IP=""',
    '# AGI_SSH_KEY_PATH=""',
    '# AGILAB_SHARE_USER="<user>"',
    '# AGILAB_CLUSTER_SHARE_BACKEND="sshfs"',
    '# AGI_CLUSTER_SHARE_BACKEND="sshfs"',
    '# AGILAB_SCHEDULER_SSH_PORT="22"',
    '# AGILAB_REMOTE_CLUSTER_SHARE_PREMOUNTED="0"',
    '# AGILAB_PREMOUNTED_REMOTE_CLUSTER_SHARE="0"',
    '# AGILAB_CLUSTER_SHARE_PREMOUNTED="0"',
    '# AGILAB_CLUSTER_SSH_HOST_KEY_POLICY="strict"',
    '# AGILAB_CLUSTER_SSH_KNOWN_HOSTS="~/.ssh/known_hosts"',
    '# AGI_CLUSTER_SSH_HOST_KEY_POLICY="strict"',
    '# AGI_CLUSTER_SSH_KNOWN_HOSTS="~/.ssh/known_hosts"',
    '# AGILAB_LAN_CLUSTER_IPS=""',
    '# AGILAB_LAN_CLUSTER_CREDENTIALS=""',
    '# AGILAB_LAN_CLUSTER_SSH_KEY_PATH=""',
    '# TABLE_MAX_ROWS="1000000"',
    '# AGI_INTERNET_ON="1"',
    '# AGILAB_UI_HOST="127.0.0.1"',
    '# AGILAB_PUBLIC_BIND_OK="0"',
    '# AGILAB_AUTH_REQUIRED="0"',
    '# AGILAB_PUBLIC_AUTH="0"',
    '# AGILAB_TLS_TERMINATED="0"',
    '# AGILAB_PUBLIC_BIND_EVIDENCE=""',
    '# AGILAB_LINK_COMPATIBLE_VENVS="1"',
    '# AGILAB_REFRESH_WORKER_ENVS="0"',
    '# AGILAB_SHARED_WORKER_VENV="1"',
    '# AGILAB_SHARED_WORKER_VENV_DIR=""',
    '# AGILAB_VENV_LINK_REPORT="~/.local/share/agilab/venv_link_report.json"',
    '# AGILAB_POOL_MAX_WORKERS=""',
    '# AGILAB_POOL_ITEM_TIMEOUT=""',
    '# AGILAB_POOL_EXECUTOR="auto"',
    '# AGILAB_RUNTIME_AUTO_INSTALL="0"',
    '# AGILAB_DISABLE_BACKGROUND_SERVICES="0"',
    '# AGILAB_DISABLE_HARDWARE_PROBES="0"',
    '# AGILAB_RUNTIME_DIAGNOSTICS_VERBOSE="0"',
    '# AGILAB_DEV_OUTPUT="summary"',
    '# AGILAB_DEV_SUMMARY_LINES="40"',
    '# AGILAB_DEV_UV_PROJECT_ENVIRONMENT=".venv-dev"',
    '# AGILAB_DISABLE_UI_DISCOVERY_CACHE="0"',
    '# AGILAB_DISABLE_ANALYSIS_DISCOVERY_CACHE="0"',
    '# AGILAB_DISABLE_PAGE_MODULE_CACHE="0"',
    '# AGILAB_NOTEBOOK_EXPORT_ALLOW_WORKSPACE_SIBLINGS="0"',
    '# AGILAB_NOTEBOOK_REUSE_REFRESH_SECONDS="8"',
    '# AGILAB_PIPELINE_LOCK_TTL_SEC="21600"',
    '# AGILAB_PREVIEW_MAX_SEARCH_FILES="1000"',
    '# AGILAB_PREVIEW_MAX_FILE_BYTES="26214400"',
    '# AGILAB_GENERATED_CODE_SANDBOX=""',
    '# AGILAB_GENERATED_CODE_PROCESS_LIMITS="0"',
    '# AGILAB_GENERATED_CODE_AUTORUN="0"',
    '# AGILAB_MCP_ALLOWED_ROOTS=""',
    '# AGILAB_MCP_ALLOW_CWD="0"',
    '# AGILAB_KEYRING_SERVICE="agilab"',
    '# AGILAB_KEYRING_ACCOUNT="<user>"',
)

CLUSTER_ENV_DEFAULT_COMMENT_KEYS = frozenset(
    {
        "IS_SOURCE_ENV",
        "IS_WORKER_ENV",
        "AGI_CLUSTER_SHARE",
        "AGI_LOCAL_SHARE",
        "AGILAB_WORKFLOW_DATA_ROOT",
        "CLUSTER_CREDENTIALS",
        "AGI_CLUSTER_ENABLED",
        "AGI_WORKERS",
        "AGI_SCHEDULER_IP",
        "AGI_SSH_KEY_PATH",
        "AGILAB_SHARE_USER",
        "AGILAB_SCHEDULER_SSH_PORT",
        "AGILAB_REMOTE_CLUSTER_SHARE_PREMOUNTED",
        "AGILAB_PREMOUNTED_REMOTE_CLUSTER_SHARE",
        "AGILAB_CLUSTER_SHARE_PREMOUNTED",
        "AGILAB_CLUSTER_SSH_HOST_KEY_POLICY",
        "AGILAB_CLUSTER_SSH_KNOWN_HOSTS",
        "AGI_CLUSTER_SSH_HOST_KEY_POLICY",
        "AGI_CLUSTER_SSH_KNOWN_HOSTS",
        "AGILAB_LAN_CLUSTER_IPS",
        "AGILAB_LAN_CLUSTER_CREDENTIALS",
        "AGILAB_LAN_CLUSTER_SSH_KEY_PATH",
        "AGILAB_POOL_MAX_WORKERS",
        "AGILAB_POOL_ITEM_TIMEOUT",
        "AGILAB_POOL_EXECUTOR",
        "AGILAB_SHARED_WORKER_VENV",
        "AGILAB_SHARED_WORKER_VENV_DIR",
    }
)


def env_default_comment_key(line: str) -> str:
    text = line.strip()
    if text.startswith("#"):
        text = text[1:].strip()
    return text.split("=", 1)[0].strip()


CLUSTER_ENV_DEFAULT_COMMENT_LINES: tuple[str, ...] = tuple(
    line
    for line in USER_ENV_DEFAULT_COMMENT_LINES
    if env_default_comment_key(line) in CLUSTER_ENV_DEFAULT_COMMENT_KEYS
)


__all__ = [
    "CLUSTER_ENV_DEFAULT_COMMENT_KEYS",
    "CLUSTER_ENV_DEFAULT_COMMENT_LINES",
    "USER_ENV_DEFAULT_COMMENT_LINES",
    "env_default_comment_key",
]
