[args]
data_source = "file"
data_uri = "data/flight/dataset"
files = "csv/*"
nfile = 10
nskip = 0
nread = 10
sampling_rate = 1.0
datemin = "2020-01-01"
datemax = "2021-01-01"
output_format = "parquet"

[pages]
app_pages = [
    "view_maps",
    "view_maps-3d",
    "view_autoencoder_latentspace",
    "view_maps-network",
    "view_barycentric",
]

[cluster]
verbose = true
cython = false
cluster_enabled = true
rapids = false
pool = false
scheduler = "127.0.0.1"

[cluster.workers]
"127.0.0.1" = 2

[views]
view_module = [
    "view_maps",
    "view_maps_3d",
    "view_maps_network",
]
