"""AGILab environment bootstrapper and utility helpers.

The module exposes the :class:`AgiEnv` class which orchestrates project discovery,
virtual-environment management, packaging helpers, and convenience utilities used
by installers as well as runtime workers.  Supporting free functions provide small
parsing and path utilities leveraged during setup."""

import shlex
from IPython.core.ultratb import FormattedTB
import ast
import asyncio
import getpass
import os
import re
import shutil
import psutil
import socket
import subprocess
import sys
import traceback
from pathlib import Path, PureWindowsPath, PurePosixPath
from dotenv import dotenv_values, set_key
import tomlkit
import logging
import astor
from pathspec import PathSpec
from pathspec.patterns import GitWildMatchPattern
import py7zr
import urllib.request
import inspect
import ctypes
from ctypes import wintypes
import importlib.util
from concurrent.futures import ThreadPoolExecutor
from agi_env.agi_logger import AgiLogger
from typing import Any

_sig = inspect.signature(FormattedTB.__init__).parameters

_tb_kwargs = dict(mode='Verbose', call_pdb=True)

sys.excepthook = FormattedTB(**_tb_kwargs)

LEVEL_RES = [
    # Optional leading time like "11:20:03 " or "11:20:03,123 "
    re.compile(r'^\s*(?:\d{2}:\d{2}:\d{2}(?:[.,]\d+)?\s+)?(DEBUG|INFO|WARNING|ERROR|CRITICAL)\b', re.IGNORECASE),
    # Bracketed level: "[ERROR] something"
    re.compile(r'^\s*\[\s*(DEBUG|INFO|WARNING|ERROR|CRITICAL)\s*\]\b', re.IGNORECASE),
    # Key/value style: "level=error ..."
    re.compile(r'\blevel\s*=\s*(debug|info|warning|error|critical)\b', re.IGNORECASE),
]

TIME_LEVEL_PREFIX = re.compile(
    r'^\s*(?:\d{2}:\d{2}:\d{2}(?:[.,]\d+)?)\s+(DEBUG|INFO|WARNING|ERROR|CRITICAL)\s*[:-]?\s*',
    re.IGNORECASE,
)

def normalize_path(*args: Any, **kwargs: Any) -> Any: ...

def parse_level(*args: Any, **kwargs: Any) -> Any: ...

def strip_time_level_prefix(*args: Any, **kwargs: Any) -> Any: ...

def is_packaging_cmd(*args: Any, **kwargs: Any) -> Any: ...

class AgiEnv:
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_package_root(*args: Any, **kwargs: Any) -> Any: ...
    def _collect_pythonpath_entries(self) -> Any: ...
    def _configure_pythonpath(self, *args: Any, **kwargs: Any) -> Any: ...
    def _dedupe_paths(*args: Any, **kwargs: Any) -> Any: ...
    def has_agilab_anywhere_under_home(self, *args: Any, **kwargs: Any) -> Any: ...
    def active(self, *args: Any, **kwargs: Any) -> Any: ...
    def humanize_validation_errors(self, *args: Any, **kwargs: Any) -> Any: ...
    def set_env_var(*args: Any, **kwargs: Any) -> Any: ...
    def read_agilab_path(*args: Any, **kwargs: Any) -> Any: ...
    def locate_agilab_installation(*args: Any, **kwargs: Any) -> Any: ...
    def copy_existing_projects(self, *args: Any, **kwargs: Any) -> Any: ...
    def _update_env_file(*args: Any, **kwargs: Any) -> Any: ...
    def _init_resources(self, *args: Any, **kwargs: Any) -> Any: ...
    def _init_projects(self) -> Any: ...
    def get_projects(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_base_worker_cls(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_base_classes(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_import_mapping(self, *args: Any, **kwargs: Any) -> Any: ...
    def extract_base_info(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_full_attribute_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def mode2str(self, *args: Any, **kwargs: Any) -> Any: ...
    def mode2int(*args: Any, **kwargs: Any) -> Any: ...
    def is_valid_ip(self, *args: Any, **kwargs: Any) -> Any: ...
    def init_envars_app(self, *args: Any, **kwargs: Any) -> Any: ...
    def _copy_file(*args: Any, **kwargs: Any) -> Any: ...
    def _init_apps(self) -> Any: ...
    def _build_env(*args: Any, **kwargs: Any) -> Any: ...
    def log_info(*args: Any, **kwargs: Any) -> Any: ...
    def run(*args: Any, **kwargs: Any) -> Any: ...
    def _run_bg(*args: Any, **kwargs: Any) -> Any: ...
    def run_agi(self, *args: Any, **kwargs: Any) -> Any: ...
    def run_async(*args: Any, **kwargs: Any) -> Any: ...
    def create_symlink(*args: Any, **kwargs: Any) -> Any: ...
    def change_active_app(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_local(*args: Any, **kwargs: Any) -> Any: ...
    def has_admin_rights(*args: Any, **kwargs: Any) -> Any: ...
    def create_junction_windows(*args: Any, **kwargs: Any) -> Any: ...
    def create_symlink_windows(*args: Any, **kwargs: Any) -> Any: ...
    def create_rename_map(self, *args: Any, **kwargs: Any) -> Any: ...
    def clone_project(self, *args: Any, **kwargs: Any) -> Any: ...
    def clone_directory(self, *args: Any, **kwargs: Any) -> Any: ...
    def _cleanup_rename(self, *args: Any, **kwargs: Any) -> Any: ...
    def replace_content(self, *args: Any, **kwargs: Any) -> Any: ...
    def read_gitignore(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_valid_ip(self, *args: Any, **kwargs: Any) -> Any: ...
    def unzip_data(self, *args: Any, **kwargs: Any) -> Any: ...
    def check_internet(*args: Any, **kwargs: Any) -> Any: ...

class ContentRenamer(ast.NodeTransformer):
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_Name(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_Attribute(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_FunctionDef(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_ClassDef(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_arg(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_Global(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_nonlocal(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_Assign(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_AnnAssign(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_For(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_Import(self, *args: Any, **kwargs: Any) -> Any: ...
    def visit_ImportFrom(self, *args: Any, **kwargs: Any) -> Any: ...
