[project]
name = "view-barycentric-graph"
version = "0.8.17"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.5.0",
    "streamlit>=1.49.1",
    "watchdog>=6.0.0",
    "agi-env",
    "plotly>=6.3.0",
    "barviz>=1.2.2",
    "scikit-learn>=1.7.2",
    "sqlalchemy>=2.0.43",
]

[optional-dependencies]
dev = [
    "agi-env",
]

[tool.uv.sources.agi-env]
path = "../../core/agi-env"
editable = true

