import logging
import warnings
from pathlib import Path
from typing import Any, List, Tuple
import py7zr
from agi_cluster.agi_distributor import AGI
from agi_node.agi_dispatcher import BaseWorker, WorkDispatcher
from .polars_app_args import (
    ArgsOverrides,
    PolarsAppArgs,
)

logger = logging.getLogger(__name__)

class Polars(BaseWorker):
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def _extend_payload(self, *args: Any, **kwargs: Any) -> Any: ...
    def _ensure_dataset(self, *args: Any, **kwargs: Any) -> Any: ...
    def pool_init(*args: Any, **kwargs: Any) -> Any: ...
    def work_pool(self, *args: Any, **kwargs: Any) -> Any: ...
    def work_done(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop(self) -> Any: ...
    def build_distribution(self) -> Any: ...
