import os
import sys
import importlib
from math import sqrt, cos, sin, ceil, pi
import numpy as np
from pathlib import Path
import streamlit as st
import pandas as pd
import argparse
from barviz import Simplex, Collection, Scrawler, Attributes
from agi_env import AgiEnv
from agi_env.pagelib import render_logo, find_files, load_df, sidebar_views, on_df_change
from typing import Any

def _ensure_repo_on_path(*args: Any, **kwargs: Any) -> Any: ...

def _default_active_app(*args: Any, **kwargs: Any) -> Any: ...

var = ["discrete", "continuous", "lat", "long"]

var_default = [0, None]

os.environ["TF_ENABLE_ONEDNN_OPTS"] = "0"

def lazy_import_plotly(*args: Any, **kwargs: Any) -> Any: ...

def lazy_import_barviz(*args: Any, **kwargs: Any) -> Any: ...

def lazy_import_keras(*args: Any, **kwargs: Any) -> Any: ...

def lazy_import_sklearn(*args: Any, **kwargs: Any) -> Any: ...

class ModifiedScrawler(Scrawler):
    def plot(self, *args: Any, **kwargs: Any) -> Any: ...

class ModifiedSimplex(Simplex):
    def __init__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __create_simplex_points(self, *args: Any, **kwargs: Any) -> Any: ...

def build_AE(*args: Any, **kwargs: Any) -> Any: ...

def __normalize_data(*args: Any, **kwargs: Any) -> Any: ...

def __bary_visualisation(*args: Any, **kwargs: Any) -> Any: ...

def update_var(*args: Any, **kwargs: Any) -> Any: ...

def update_datadir(*args: Any, **kwargs: Any) -> Any: ...

def page(*args: Any, **kwargs: Any) -> Any: ...

def main(*args: Any, **kwargs: Any) -> Any: ...
