import os
import sys
import argparse
from pathlib import Path
import parso
from typing import Any

def get_decorator_name(*args: Any, **kwargs: Any) -> Any: ...

def process_decorators(*args: Any, **kwargs: Any) -> Any: ...

def remove_decorators(*args: Any, **kwargs: Any) -> Any: ...

def prepare_for_cython(*args: Any, **kwargs: Any) -> Any: ...

def main(*args: Any, **kwargs: Any) -> Any: ...
