[project]
name = "ilp_worker"
version = "0.8.17"
description = "ILP worker dependencies"
requires-python = ">=3.11"
readme = "../../README.md"

dependencies = [
    "gymnasium",
    "matplotlib",
    "networkx",
    "numpy",
    "pulp",
    "pandas",
]

authors = [
    { name = "AGILab Team" }
]

[project.license]
text = "Thales SIX GTS France SAS"

[dependency-groups]
dev = [
    "black",
    "pytest",
    "pytest-asyncio",
    "licensecheck",
]

[tool.uv.sources.ilp_worker]
workspace = true

[project.optional-dependencies]
dag-worker = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
ilp_worker = [
    "data/*.txt",
]
