from __future__ import annotations
import inspect
import logging
import os
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Dict, Iterable, List, Mapping
from agi_node.agi_dispatcher import BaseWorker

class DagWorker(BaseWorker):
    def get_work(self, *args: Any, **kwargs: Any) -> Any: ...
    def _invoke(self, *args: Any, **kwargs: Any) -> Any: ...
    def works(self, *args: Any, **kwargs: Any) -> Any: ...
    def _exec_mono_process(self, *args: Any, **kwargs: Any) -> Any: ...
    def _topological_sort(*args: Any, **kwargs: Any) -> Any: ...
    def _exec_multi_process(self, *args: Any, **kwargs: Any) -> Any: ...
