from __future__ import annotations

import json
import os
import subprocess
import sys
import tomllib
from contextlib import contextmanager
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Any, Callable, Dict, List, Optional, Pattern, Type

from agi_env import AgiEnv


def to_bool_flag(value: Any, default: bool = False) -> bool:
    """Convert settings values to bool with tolerant parsing."""
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y", "on"}
    return default


def safe_service_start_template(env: AgiEnv, marker: str) -> str:
    """Build an idempotent AGI.serve(start) snippet for PIPELINE import."""
    settings: Dict[str, Any] = {}
    try:
        app_settings_path = Path(env.app_settings_file)
        if app_settings_path.exists():
            with app_settings_path.open("rb") as stream:
                loaded = tomllib.load(stream)
            if isinstance(loaded, dict):
                settings = loaded
    except (AttributeError, OSError, RuntimeError, TypeError, ValueError, tomllib.TOMLDecodeError):
        settings = {}

    cluster = settings.get("cluster", {}) if isinstance(settings.get("cluster"), dict) else {}
    run_args = settings.get("args", {}) if isinstance(settings.get("args"), dict) else {}

    cluster_enabled = to_bool_flag(cluster.get("cluster_enabled"), False)
    pool = to_bool_flag(cluster.get("pool"), False)
    cython = to_bool_flag(cluster.get("cython"), False)
    rapids = to_bool_flag(cluster.get("rapids"), False)
    mode = int(pool) + int(cython) * 2 + int(cluster_enabled) * 4 + int(rapids) * 8
    scheduler = cluster.get("scheduler") if cluster.get("scheduler") else None
    workers = cluster.get("workers") if isinstance(cluster.get("workers"), dict) else None
    verbose_raw = cluster.get("verbose", 1)
    try:
        verbose = int(verbose_raw)
    except (TypeError, ValueError):
        verbose = 1

    def _safe_literal(value: Any) -> str:
        if value is None:
            return "None"
        if isinstance(value, bool):
            return "True" if value else "False"
        if isinstance(value, int):
            return str(value)
        if isinstance(value, str):
            return json.dumps(value)
        return json.dumps(value)

    apps_path_lit = _safe_literal(str(env.apps_path))
    app_lit = _safe_literal(str(env.app))
    scheduler_lit = _safe_literal(scheduler)
    workers_lit = _safe_literal(workers) if workers is None else f"json.loads({json.dumps(json.dumps(workers))})"
    run_args_lit = _safe_literal(run_args) if run_args is None else f"json.loads({json.dumps(json.dumps(run_args))})"
    needs_json = workers is not None or run_args is not None
    json_import = "\nimport json" if needs_json else ""

    return f"""{marker}
import asyncio{json_import}
from agi_cluster.agi_distributor import AGI
from agi_env import AgiEnv

APPS_PATH = {apps_path_lit}
APP = {app_lit}
VERBOSE = {int(verbose)}
MODE = {int(mode)}
SCHEDULER = {scheduler_lit}
WORKERS = {workers_lit}
RUN_ARGS = {run_args_lit}

async def safe_service_start():
    app_env = AgiEnv(apps_path=APPS_PATH, app=APP, verbose=VERBOSE)
    if MODE & 4 == 0:
        raise RuntimeError(
            "Cluster (Dask) is disabled in app_settings.toml. "
            "Enable cluster before starting AGI.serve."
        )

    status = await AGI.serve(
        app_env,
        action="status",
        mode=MODE,
        scheduler=SCHEDULER,
        workers=WORKERS,
        **RUN_ARGS,
    )
    state = str((status or {{}}).get("status", "")).lower()

    if state in {{"running", "degraded"}}:
        print("Service already running; start skipped.")
        print(status)
        return status

    if state == "error":
        await AGI.serve(
            app_env,
            action="stop",
            mode=MODE,
            scheduler=SCHEDULER,
            workers=WORKERS,
            **RUN_ARGS,
        )

    result = await AGI.serve(
        app_env,
        action="start",
        mode=MODE,
        scheduler=SCHEDULER,
        workers=WORKERS,
        **RUN_ARGS,
    )
    print(result)
    return result

if __name__ == "__main__":
    asyncio.run(safe_service_start())
"""


def ensure_safe_service_template(
    env: AgiEnv,
    steps_file: Path,
    *,
    template_filename: str,
    marker: str,
    debug_log: Callable[[str, Any], None],
) -> Optional[Path]:
    """Create or update an autogenerated safe service snippet file near lab steps."""
    template_path = steps_file.parent / template_filename
    content = safe_service_start_template(env, marker)
    try:
        existing = template_path.read_text(encoding="utf-8") if template_path.exists() else None
        if existing == content:
            return template_path
        if existing:
            first_line = existing.splitlines()[0].strip()
            if first_line and first_line != marker:
                return template_path
        template_path.parent.mkdir(parents=True, exist_ok=True)
        template_path.write_text(content, encoding="utf-8")
        return template_path
    except OSError as exc:
        debug_log("Unable to ensure safe service template at %s: %s", template_path, exc)
        return None


def build_mlflow_process_env(
    env: AgiEnv,
    *,
    tracking_uri: str,
    step_run_id_env: str,
    run_id: str | None = None,
    base_env: Optional[Dict[str, str]] = None,
) -> Dict[str, str]:
    """Inject the shared tracking URI into a child process environment."""
    process_env = dict(base_env or os.environ.copy())
    process_env["MLFLOW_TRACKING_URI"] = tracking_uri
    apps_path = getattr(env, "apps_path", None)
    if apps_path:
        process_env["APPS_PATH"] = str(apps_path)
    if run_id:
        process_env[step_run_id_env] = str(run_id)
        process_env["MLFLOW_RUN_ID"] = str(run_id)
    else:
        process_env.pop(step_run_id_env, None)
        process_env.pop("MLFLOW_RUN_ID", None)
    return process_env


def truncate_mlflow_text(value: Any, limit: int = 500) -> str:
    """Convert arbitrary values into bounded MLflow-safe strings."""
    text = "" if value is None else str(value)
    if limit <= 0 or len(text) <= limit:
        return text
    if limit == 1:
        return text[:1]
    return text[: limit - 1] + "…"


@contextmanager
def temporary_env_overrides(overrides: Optional[Dict[str, Any]]):
    """Temporarily apply environment overrides for in-process step execution."""
    if not overrides:
        yield
        return

    sentinel = object()
    previous = {key: os.environ.get(key, sentinel) for key in overrides}
    try:
        for key, value in overrides.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = str(value)


@contextmanager
def start_mlflow_run(
    env: AgiEnv,
    *,
    run_name: str,
    tags: Optional[Dict[str, Any]] = None,
    params: Optional[Dict[str, Any]] = None,
    nested: bool = False,
    get_mlflow_module_fn: Callable[[], Any | None],
    ensure_default_mlflow_experiment_fn: Callable[[AgiEnv, Any], str | None],
    truncate_text_fn: Callable[[Any, int], str] = truncate_mlflow_text,
):
    """Open an MLflow run against the sidebar tracking store when MLflow is available."""
    mlflow = get_mlflow_module_fn()
    if mlflow is None:
        yield None
        return

    tracking_uri = ensure_default_mlflow_experiment_fn(env, mlflow)
    clean_tags = {
        str(key): truncate_text_fn(value, 5000)
        for key, value in (tags or {}).items()
        if value is not None
    }
    clean_params = {
        str(key): truncate_text_fn(value, 500)
        for key, value in (params or {}).items()
        if value is not None
    }
    run_kwargs: Dict[str, Any] = {"run_name": run_name}
    if nested:
        run_kwargs["nested"] = True

    with mlflow.start_run(**run_kwargs) as run:
        if clean_tags:
            mlflow.set_tags(clean_tags)
        if clean_params:
            mlflow.log_params(clean_params)
        yield {"mlflow": mlflow, "run": run, "tracking_uri": tracking_uri}


def log_mlflow_artifacts(
    tracking: Optional[Dict[str, Any]],
    *,
    text_artifacts: Optional[Dict[str, Any]] = None,
    file_artifacts: Optional[List[str | Path]] = None,
    tags: Optional[Dict[str, Any]] = None,
    metrics: Optional[Dict[str, float]] = None,
    truncate_text_fn: Callable[[Any, int], str] = truncate_mlflow_text,
) -> None:
    """Log text/file artifacts plus final tags/metrics to an active MLflow run."""
    if not tracking:
        return

    mlflow = tracking["mlflow"]
    if tags:
        mlflow.set_tags(
            {
                str(key): truncate_text_fn(value, 5000)
                for key, value in tags.items()
                if value is not None
            }
        )
    if metrics:
        for key, value in metrics.items():
            if value is None:
                continue
            try:
                mlflow.log_metric(str(key), float(value))
            except Exception:
                continue
    for artifact_name, text in (text_artifacts or {}).items():
        if text is None:
            continue
        payload = str(text)
        if hasattr(mlflow, "log_text"):
            mlflow.log_text(payload, artifact_name)
        else:
            with NamedTemporaryFile("w", encoding="utf-8", suffix=Path(artifact_name).suffix or ".txt", delete=False) as tmp:
                tmp.write(payload)
                tmp_path = Path(tmp.name)
            try:
                mlflow.log_artifact(str(tmp_path), artifact_path=str(Path(artifact_name).parent))
            finally:
                tmp_path.unlink(missing_ok=True)
    for artifact in file_artifacts or []:
        if not artifact:
            continue
        artifact_path = Path(artifact).expanduser()
        if artifact_path.exists():
            mlflow.log_artifact(str(artifact_path))

        yield
    finally:
        for key, value in previous.items():
            if value is sentinel:
                os.environ.pop(key, None)
            else:
                os.environ[key] = str(value)


def python_for_venv(venv_root: str | Path | None, *, sys_executable: str | None = None) -> Path:
    """Return a python executable for a runtime selection."""
    if not venv_root:
        return Path(sys_executable or sys.executable)

    root = Path(venv_root).expanduser()
    venv_candidates = [root]
    project_venv = root / ".venv"
    if project_venv.exists():
        venv_candidates.insert(0, project_venv)

    for venv in venv_candidates:
        for candidate in (
            venv / "bin" / "python",
            venv / "bin" / "python3",
            venv / "Scripts" / "python.exe",
            venv / "Scripts" / "python",
        ):
            if candidate.exists():
                return candidate

    return Path(sys_executable or sys.executable)


def uses_controller_python(engine: str | None, code: str | None) -> bool:
    """Return True when a step should execute in the current AGILab/controller env."""
    if not str(engine or "").startswith("agi."):
        return False
    text = str(code or "")
    return (
        "from agi_cluster.agi_distributor import AGI" in text
        or "import agi_cluster" in text
        or "AGI.install(" in text
        or "AGI.run(" in text
        or "AGI.serve(" in text
        or "AGI.get_distrib(" in text
    )


def python_for_step(
    venv_root: str | Path | None,
    *,
    engine: str | None,
    code: str | None,
    sys_executable: str | None = None,
) -> Path:
    """Choose the python executable for one step."""
    if uses_controller_python(engine, code):
        return Path(sys_executable or sys.executable)
    return python_for_venv(venv_root, sys_executable=sys_executable)


def label_for_step_runtime(
    venv_root: str | Path | None,
    *,
    engine: str | None,
    code: str | None,
    sys_executable: str | None = None,
) -> str:
    """Return a readable runtime label for the step log."""
    if uses_controller_python(engine, code):
        executable = Path(sys_executable or sys.executable)
        target = Path(venv_root).name if venv_root else str(getattr(executable, "name", "python"))
        return f"controller env -> {target}"
    return Path(venv_root).name if venv_root else "default env"


def is_valid_runtime_root(venv_root: str | Path | None) -> bool:
    """Return True when the runtime root points at an existing project/venv."""
    if not venv_root:
        return False
    try:
        root = Path(venv_root).expanduser()
    except (OSError, RuntimeError, TypeError, ValueError):
        return False
    if not root.exists():
        return False
    if (root / ".venv").exists():
        return True
    for candidate in (
        root / "bin" / "python",
        root / "bin" / "python3",
        root / "Scripts" / "python.exe",
        root / "Scripts" / "python",
    ):
        if candidate.exists():
            return True
    return False


def stream_run_command(
    env: AgiEnv,
    index_page: str,
    cmd: str,
    cwd: Path,
    *,
    push_run_log: Callable[[str, str, Optional[Any]], None],
    ansi_escape_re: Pattern[str],
    jump_exception_cls: Type[BaseException],
    placeholder: Optional[Any] = None,
    extra_env: Optional[Dict[str, str]] = None,
    timeout: Optional[int] = None,
    env_vars: Optional[Dict[str, str]] = None,
    popen_factory: Callable[..., Any] = subprocess.Popen,
    path_separator: str = os.pathsep,
) -> str:
    """Run a shell command and stream its output into the run log."""
    process_env = dict(env_vars or os.environ.copy())
    process_env["uv_IGNORE_ACTIVE_VENV"] = "1"
    apps_root = getattr(env, "apps_path", None)
    extra_python_paths: List[str] = []
    if apps_root:
        try:
            apps_root = Path(apps_root).expanduser()
            src_root = apps_root.parent.parent
            if (src_root / "agilab").is_dir():
                extra_python_paths.append(str(src_root))
        except (OSError, RuntimeError, TypeError, ValueError):
            pass
    if extra_python_paths:
        existing = process_env.get("PYTHONPATH")
        joined = path_separator.join(extra_python_paths + ([existing] if existing else []))
        process_env["PYTHONPATH"] = joined
    if extra_env:
        process_env.update({str(key): str(value) for key, value in extra_env.items() if value is not None})

    lines: List[str] = []
    with popen_factory(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        shell=True,
        cwd=Path(cwd).resolve(),
        env=process_env,
        text=True,
        bufsize=1,
    ) as proc:
        try:
            assert proc.stdout is not None
            for raw_line in proc.stdout:
                cleaned = ansi_escape_re.sub("", raw_line.rstrip())
                if cleaned:
                    lines.append(cleaned)
                    push_run_log(index_page, cleaned, placeholder)
            proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            proc.kill()
            push_run_log(index_page, f"Command timed out after {timeout} seconds.", placeholder)
        except subprocess.CalledProcessError as err:
            proc.kill()
            push_run_log(index_page, f"Command failed: {err}", placeholder)
        combined = "\n".join(lines).strip()
        lowered = combined.lower()
        if "module not found" in lowered:
            apps_root = env.apps_path
            if apps_root and not (Path(apps_root) / ".venv").exists():
                raise jump_exception_cls(combined)
        return combined


def wrap_code_with_mlflow_resume(code: str, *, step_run_id_env: str) -> str:
    """Resume a controller-created MLflow run inside subprocess-executed user code."""
    body = code if code.endswith("\n") else code + "\n"
    indented = "".join(f"    {line}\n" for line in body.splitlines()) if body.strip() else "    pass\n"
    return (
        "import os\n"
        "_agilab_mlflow = None\n"
        "_agilab_active_run = None\n"
        "try:\n"
        "    import mlflow as _agilab_mlflow\n"
        "    _agilab_tracking_uri = os.environ.get('MLFLOW_TRACKING_URI')\n"
        "    if _agilab_tracking_uri:\n"
        "        _agilab_mlflow.set_tracking_uri(_agilab_tracking_uri)\n"
        f"    _agilab_run_id = os.environ.get('{step_run_id_env}') or os.environ.get('MLFLOW_RUN_ID')\n"
        "    if _agilab_run_id:\n"
        "        _agilab_active_run = _agilab_mlflow.start_run(run_id=_agilab_run_id)\n"
        "except Exception:\n"
        "    _agilab_mlflow = None\n"
        "    _agilab_active_run = None\n"
        "\n"
        "try:\n"
        f"{indented}"
        "finally:\n"
        "    if _agilab_active_run is not None and _agilab_mlflow is not None:\n"
        "        try:\n"
        "            _agilab_mlflow.end_run()\n"
        "        except Exception:\n"
        "            pass\n"
    )
