[project]
name = "network_sim_worker"
version = "0.1.0"
description = "Worker package for the Network Simulation app"
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "agi-env",
    "agi-node",
    "networkx",
    "numpy",
]

[project.license]
text = "Thales SIX GTS France SAS"

[dependency-groups]
dev = [
    "black",
    "pytest",
    "licensecheck",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
mypy_path = ["stubs"]
disallow_untyped_defs = false
ignore_missing_imports = true

[tool.uv.sources]
agi-env = { path = "../../PycharmProjects/agilab/src/agilab/core/agi-env" }
agi-node = { path = "../../PycharmProjects/agilab/src/agilab/core/agi-node" }

[project.optional-dependencies]
dag-worker = []
