[project]
name = "network_sim_worker"
version = "0.1.0"
description = "Worker package for the Network Simulation app"
requires-python = ">=3.11"
readme = "README.md"
dependencies = [
    "networkx",
    "numpy",
    "astor",
    "asyncssh",
    "build",
    "cmake>=3.29",
    "fastparquet",
    "geojson",
    "humanize",
    "jupyter-ai[all]",
    "keras",
    "matplotlib",
    "mlflow",
    "numba",
    "numpy>=1.14.1",
    "openai",
    "pathspec",
    "pip",
    "plotly",
    "polars",
    "pulp",
    "py7zr",
    "scipy==1.15.2",
    "seaborn",
    "setuptools",
    "streamlit",
    "streamlit-modal",
    "streamlit_code_editor",
    "streamlit_extras",
    "tomli",
    "tomli_w",
    "twine",
    "watchdog",
    "wheel",
    "legacy-cgi",
    "standard-imghdr",
    "pydantic",
    "python-dotenv",
    "tomlkit",
    "psutil",
    "ipython",
    "scikit-learn",
    "parso",
    "cython",
    "msgpack",
    "dask[distributed]",
    "typing-inspection>=0.4.1",
    "pandas",
    "jupyter",
    "mypy",
    "requests",
    "scp",
]

[project.license]
text = "Thales SIX GTS France SAS"

[project.optional-dependencies]
dag-worker = []









[dependency-groups]
dev = [
    "black",
    "pytest",
    "pytest-cov",
    "licensecheck",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.mypy]
mypy_path = ["stubs"]
disallow_untyped_defs = false
ignore_missing_imports = true
