[args]
data_source = "file"
data_in = "network_sim/dataset"
flows_dir = "flows"
link_results_dir = "link_insights"
topology_filename = "ilp_topology.gml"
summary_filename = "topology_summary.json"
demands_filename = "ilp_demands.json"

[cluster]
verbose = 1
cython = true
pool = true
rapids = true
cluster_enabled = true
user = "agi"
auth_method = "password"
scheduler = "192.168.20.111"

[cluster.workers]
"192.168.20.111" = 1
