[args]
data_source = "file"
data_uri = "data/network_sim/dataset"
net_size = 12
seed = 42
topology_filename = "topology.gml"
summary_filename = "topology_summary.json"

[cluster]
verbose = 1
cython = true
pool = true
rapids = true
cluster_enabled = false
