#!/usr/bin/env python3
from __future__ import annotations
import os
import sys
import subprocess
import xml.etree.ElementTree as ET
from xml.dom import minidom
from pathlib import Path
from typing import Optional, List

# ----------------------------- paths / constants ----------------------------- #
ROOT = Path.cwd()
IDEA = ROOT / ".idea"
MODULES_DIR = IDEA / "modules"
RUNCFG_DIR = IDEA / "runConfigurations"   # generated by gen-app-script.py
APPS_DIR = ROOT / "src" / "agilab" / "apps"
GEN_SCRIPT = ROOT / "pycharm" / "gen-app-script.py"

SDK_TYPE = "Python SDK"
PROJECT_SDK_NAME = "uv (agilab)"  # root project interpreter name

# ----------------------------- utils ----------------------------- #
def debug(msg: str) -> None:
    print(f"[install-apps] {msg}")

def pretty_write_xml(elem_or_tree: ET.Element | ET.ElementTree, dest: Path) -> None:
    """Pretty print XML to file with stable indentation."""
    if isinstance(elem_or_tree, ET.ElementTree):
        elem = elem_or_tree.getroot()
    else:
        elem = elem_or_tree
    xml_bytes = ET.tostring(elem, encoding="utf-8")
    pretty = minidom.parseString(xml_bytes).toprettyxml(indent="  ", encoding="utf-8")
    dest.parent.mkdir(parents=True, exist_ok=True)
    with dest.open("wb") as f:
        f.write(pretty)

def read_xml(path: Path) -> ET.ElementTree:
    return ET.parse(str(path))

def venv_python_for(project_dir: Path) -> Optional[Path]:
    """Return the project's .venv python, if present."""
    candidates = [
        project_dir / ".venv" / "bin" / "python3",        # unix/mac
        project_dir / ".venv" / "bin" / "python",         # unix/mac alt
        project_dir / ".venv" / "Scripts" / "python.exe", # windows
    ]
    for c in candidates:
        if c.exists():
            return c.resolve()
    return None

# ----------------------------- modules.xml / .iml ----------------------------- #
def ensure_module(app_dir: Path) -> None:
    """
    Create .idea/modules/{APP}.iml and ensure it's listed in .idea/modules.xml.
    Leaves module SDK as inherited for now (we'll override right after).
    """
    app = app_dir.name
    iml_path = MODULES_DIR / f"{app}.iml"

    if not iml_path.exists():
        m = ET.Element("module", {"type": "PYTHON_MODULE", "version": "4"})
        comp = ET.SubElement(m, "component", {"name": "NewModuleRootManager"})
        ET.SubElement(comp, "content", {"url": f"file://{app_dir}"})
        ET.SubElement(comp, "orderEntry", {"type": "inheritedJdk"})
        ET.SubElement(comp, "orderEntry", {"type": "sourceFolder", "forTests": "false"})
        pretty_write_xml(m, iml_path)
        debug(f"IML created: {iml_path}")

    modules_xml = IDEA / "modules.xml"
    if modules_xml.exists():
        tree = read_xml(modules_xml)
        root = tree.getroot()
    else:
        root = ET.Element("project", {"version": "4"})
        comp = ET.SubElement(root, "component", {"name": "ProjectModuleManager"})
        ET.SubElement(comp, "modules")
        tree = ET.ElementTree(root)

    modules = root.find("./component[@name='ProjectModuleManager']/modules")
    fileurl = f"file://{iml_path}"
    existing_urls = [m.get("fileurl") for m in modules.findall("module")]
    if fileurl not in existing_urls:
        ET.SubElement(modules, "module", {"fileurl": fileurl, "filepath": str(iml_path)})
        pretty_write_xml(tree, modules_xml)  # pretty: one <module> per line
        debug(f"modules.xml updated with {fileurl}")

def set_module_sdk(iml_path: Path, sdk_name: str) -> None:
    """
    Force a module to use a specific SDK (its own .venv) instead of inheritedJdk.
    """
    tree = read_xml(iml_path)
    root = tree.getroot()
    comp = root.find("./component[@name='NewModuleRootManager']")
    if comp is None:
        comp = ET.SubElement(root, "component", {"name": "NewModuleRootManager"})
    # remove existing jdk entries (inherited or explicit)
    for oe in list(comp.findall("orderEntry")):
        if oe.get("type") in {"inheritedJdk", "jdk"}:
            comp.remove(oe)
    ET.SubElement(comp, "orderEntry", {"type": "jdk", "jdkName": sdk_name, "jdkType": SDK_TYPE})
    pretty_write_xml(tree, iml_path)

def prune_stray_module_iml() -> None:
    """Optional: remove a leftover 'module.iml' and its entry from modules.xml if others exist."""
    stray = MODULES_DIR / "module.iml"
    modules_xml = IDEA / "modules.xml"
    if not stray.exists() or not modules_xml.exists():
        return
    try:
        if len(list(MODULES_DIR.glob("*.iml"))) > 1:
            stray.unlink()
            tree = read_xml(modules_xml)
            root = tree.getroot()
            modules = root.find("./component[@name='ProjectModuleManager']/modules")
            for el in list(modules.findall("module")):
                if el.get("filepath", "").endswith("/module.iml") or el.get("fileurl", "").endswith("/module.iml"):
                    modules.remove(el)
            pretty_write_xml(tree, modules_xml)
            debug("Removed stray module.iml and cleaned modules.xml")
    except Exception as e:
        debug(f"Prune stray module.iml skipped: {e!r}")

# ----------------------------- JetBrains SDK registry ----------------------------- #
def _jb_base_dirs() -> List[Path]:
    home = Path.home()
    bases: List[Path] = []
    if sys.platform == "darwin":
        bases.append(home / "Library" / "Application Support" / "JetBrains")
    elif os.name == "nt":
        appdata = os.environ.get("APPDATA")
        if appdata:
            bases.append(Path(appdata) / "JetBrains")
    else:
        bases.append(home / ".config" / "JetBrains")
    return [b for b in bases if b.exists()]

def _find_jdk_tables() -> List[Path]:
    tables: List[Path] = []
    for base in _jb_base_dirs():
        for product in ("PyCharm*", "PyCharmCE*"):
            for candidate in base.glob(product):
                p = candidate / "options" / "jdk.table.xml"
                if p.exists():
                    tables.append(p)
    return tables

def _load_or_init_jdk_table(path: Path) -> ET.ElementTree:
    if path.exists():
        try:
            return read_xml(path)
        except ET.ParseError:
            pass
    root = ET.Element("application")
    ET.SubElement(root, "component", {"name": "ProjectJdkTable"})
    return ET.ElementTree(root)

def _ensure_jdk_entry(tree: ET.ElementTree, name: str, home: str) -> bool:
    """
    Ensure a <jdk> entry exists/updated. Returns True if modified.
    """
    root = tree.getroot()
    comp = root.find("./component[@name='ProjectJdkTable']")
    if comp is None:
        comp = ET.SubElement(root, "component", {"name": "ProjectJdkTable"})
    # exists?
    for jdk in comp.findall("jdk"):
        nm = jdk.find("./name")
        if nm is not None and nm.get("value") == name:
            hp = jdk.find("./homePath")
            if hp is None:
                ET.SubElement(jdk, "homePath", {"value": home})
                return True
            if hp.get("value") != home:
                hp.set("value", home)
                return True
            return False
    # create
    jdk = ET.SubElement(comp, "jdk", {"version": "2"})
    ET.SubElement(jdk, "name", {"value": name})
    ET.SubElement(jdk, "type", {"value": SDK_TYPE})
    ET.SubElement(jdk, "homePath", {"value": home})
    return True

def register_sdk_globally(name: str, home_python: Path) -> None:
    modified_any = False
    for table in _find_jdk_tables():
        tree = _load_or_init_jdk_table(table)
        if _ensure_jdk_entry(tree, name, str(home_python)):
            pretty_write_xml(tree, table)
            modified_any = True
            debug(f"Registered SDK '{name}' at {home_python} in {table}")
    if not modified_any:
        debug("No JetBrains jdk.table.xml found; SDKs will still work via run configs, "
              "but IDE SDK chooser won't list them until PyCharm is launched once.")

# ----------------------------- project SDK (misc.xml) ----------------------------- #
def set_project_sdk(name: str, sdk_type: str = SDK_TYPE) -> None:
    misc = IDEA / "misc.xml"
    if misc.exists():
        tree = read_xml(misc)
        root = tree.getroot()
    else:
        root = ET.Element("project", {"version": "4"})
        tree = ET.ElementTree(root)
    prm = root.find("./component[@name='ProjectRootManager']")
    if prm is None:
        prm = ET.SubElement(root, "component", {"name": "ProjectRootManager"})
    prm.set("project-jdk-name", name)
    prm.set("project-jdk-type", sdk_type)
    pretty_write_xml(tree, misc)
    debug(f"Project SDK set to '{name}' in misc.xml")

# ----------------------------- main ----------------------------- #
def main() -> int:
    IDEA.mkdir(exist_ok=True)
    MODULES_DIR.mkdir(parents=True, exist_ok=True)
    RUNCFG_DIR.mkdir(parents=True, exist_ok=True)

    # 0) Root project SDK -> uv (agilab) bound to ROOT/.venv python
    root_py = venv_python_for(ROOT)
    if root_py:
        register_sdk_globally(PROJECT_SDK_NAME, root_py)
        set_project_sdk(PROJECT_SDK_NAME, SDK_TYPE)
    else:
        debug("Root .venv python not found; run `uv venv` at repo root if you want a project SDK.")

    # 1) Discover apps & create modules
    if not APPS_DIR.exists():
        debug(f"Apps directory not found: {APPS_DIR}")
        return 1

    apps = sorted(p for p in APPS_DIR.iterdir() if p.is_dir() and p.name.endswith("_project"))
    if not apps:
        debug("No *_project apps found.")
        return 0

    for app_dir in apps:
        app = app_dir.name
        ensure_module(app_dir)  # writes .iml + ensures modules.xml

        # Per-module venv binding (if present)
        py = venv_python_for(app_dir)
        if not py:
            debug(f"{app}: .venv python not found, leaving module on inheritedJdk.")
            continue

        # SDK name without changing your naming scheme; if you prefer stripping suffix, adjust here
        base = app[:-8] if app.endswith("_project") else app
        sdk_name = f"uv ({base})"

        register_sdk_globally(sdk_name, py)
        set_module_sdk(MODULES_DIR / f"{app}.iml", sdk_name)
        debug(f"{app}: module SDK set to '{sdk_name}' ({py})")

    # Optional: remove a stray module.iml if others exist
    prune_stray_module_iml()

    # 2) Delegate run configuration generation per app
    if not GEN_SCRIPT.exists():
        debug(f"Missing {GEN_SCRIPT}; skipping run configuration generation.")
        return 0

    for app_dir in apps:
        app = app_dir.name
        module_name = app[:-8] if app.endswith("_project") else app  # strip "_project"
        debug(f"Generating run configs for module '{module_name}' via {GEN_SCRIPT.name}...")
        subprocess.run([sys.executable, str(GEN_SCRIPT), module_name], check=True, cwd=str(ROOT))

    debug("Done.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
