import warnings
from agi_env import AgiEnv, normalize_path
from pandas_worker import PandasWorker
from typing import Any

logger = logging.getLogger(__name__)

class PandasAppWorker(PandasWorker):
    def start(self) -> Any: ...
    def work_init(self) -> Any: ...
    def pool_init(self, *args: Any, **kwargs: Any) -> Any: ...
    def work_pool(self, *args: Any, **kwargs: Any) -> Any: ...
    def work_done(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop(self) -> Any: ...
