#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<'EOF'
Usage:
  tools/capture_three_project_demo.sh [--name demo-name] [--duration 82] [--start 0] [--trim 74] [--crop x:y:w:h] [--rl-app-root /path/to/routing_project] [--print-only] [--via-terminal]

What it does:
  1. Writes a concrete cue sheet for the Mission Decision demo.
  2. Points the operator to the exact public and external project roots used for each act.
  3. Delegates the actual recording/export to tools/capture_demo_workflow.sh.

Default acts:
  - Ingest: execution_pandas_project
  - Predict: weather_forecast_project
  - Decide: uav_relay_queue_project, or another routing / optimization project passed with --rl-app-root

Examples:
  tools/capture_three_project_demo.sh
  tools/capture_three_project_demo.sh --name agilab-mission-decision --duration 82 --trim 74
  tools/capture_three_project_demo.sh --name agilab-mission-decision --duration 82 --trim 74 --via-terminal
  tools/capture_three_project_demo.sh --print-only
EOF
  exit 0
fi

NAME="agilab-mission-decision"
DURATION="82"
START="0"
TRIM="74"
CROP=""
PRINT_ONLY="0"
RL_APP_ROOT=""
VIA_TERMINAL="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      NAME="$2"
      shift 2
      ;;
    --duration)
      DURATION="$2"
      shift 2
      ;;
    --start)
      START="$2"
      shift 2
      ;;
    --trim)
      TRIM="$2"
      shift 2
      ;;
    --crop)
      CROP="$2"
      shift 2
      ;;
    --rl-app-root)
      RL_APP_ROOT="$2"
      shift 2
      ;;
    --print-only)
      PRINT_ONLY="1"
      shift
      ;;
    --via-terminal)
      VIA_TERMINAL="1"
      shift
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_RL_APP_ROOT="$ROOT/src/agilab/apps/builtin/uav_relay_queue_project"
if [[ -z "$RL_APP_ROOT" ]]; then
  RL_APP_ROOT="$DEFAULT_RL_APP_ROOT"
fi
RL_APP_LABEL="$(basename "$RL_APP_ROOT")"

DATA_APP_ROOT="$ROOT/src/agilab/apps/builtin/execution_pandas_project"
ML_APP_ROOT="$ROOT/src/agilab/apps/builtin/weather_forecast_project"

OUT_DIR="$ROOT/artifacts/demo_media/$NAME"
mkdir -p "$OUT_DIR"
PLAN_FILE="$OUT_DIR/${NAME}_cue_sheet.md"

cat > "$PLAN_FILE" <<EOF
# Mission Decision Demo Cue Sheet

This cue sheet is generated by \`tools/capture_three_project_demo.sh\`.

Preferred cut: \`70-75s\` final runtime with hard transitions and no idle waiting.

## Goal

Core idea: show AGILAB as an autonomous mission-data decision engine:

- ingest raw mission-like data
- build and replay the pipeline path from generated snippets and visible steps
- distribute computation across workers
- adapt after a bandwidth or node failure
- return an optimized routing decision with visible metrics

## Differentiation

- chatbot-style demos focus on interaction
- this demo focuses on impact and execution
- positioning line: \`AGILAB turns mission data into decisions.\`

## Scenario

Context:

- sensor-style streams
- network / satcom status
- operational constraints:
  - latency
  - bandwidth
  - risk

Objective:

- optimize routing and decision-making under dynamic constraints

## Pipeline overview

\`Data -> Cleaning -> Feature extraction -> Model selection -> Optimization / RL -> Simulation -> Decision\`

Scope note:

- show generated snippets, replayable steps, worker activity, and decision evidence
- do not claim unsupported first-class runtime DAG expansion unless that behavior is visible in the run

## Demo steps

1. Live Data Ingestion
   - simulated + real-like mission data
   - dashboard refresh or artifact update if available
2. Automatic Pipeline Generation
   - generated snippets and replayable DAG-style steps
   - adaptive workflow selection shown through the selected run path
3. Distributed Execution
   - parallel worker activity or the clearest local-worker equivalent
   - scaling claim scoped to worker distribution, not unsupported production autoscaling
4. AI + Optimization Loop
   - prediction signal
   - routing / optimization decision under constraints
5. Real-Time Adaptation
   - bandwidth drop, node failure, or risk increase
   - recompute, re-optimize, new decision
6. Final Output
   - selected strategy
   - latency down, cost down, reliability up

## Recording settings

- clip name: \`$NAME\`
- raw duration target: \`$DURATION\` seconds
- edited duration target: \`$TRIM\` seconds
- trim start: \`$START\` seconds
- crop: \`${CROP:-none}\`

## Project roots

- ingestion act: \`$DATA_APP_ROOT\`
- prediction act: \`$ML_APP_ROOT\`
- decision act: \`$RL_APP_ROOT\`

## Timeline

### Intro: 0s -> 4s

- open AGILAB
- show one opener line only:
  - \`Most AI demos answer questions. This one takes decisions.\`

### Act 1: Live data ingestion (execution_pandas_project) 4s -> 19s

- select \`execution_pandas_project\` in \`PROJECT\`
- frame the generated files as mission telemetry, sensor logs, or network status
- show dashboard refresh or artifact update if available
- show only the highest-signal ingestion settings:
  - \`nfile\`
  - \`rows_per_file\`
- move immediately to \`ORCHESTRATE\` and show one runnable compute step
- flash \`WORKFLOW\` only long enough to prove the data path is replayable
- finish on one concrete proof frame:
  - generated input artifact
  - or exported compute result
- cut as soon as the evidence is visible

### Act 2: Feature extraction and prediction (weather_forecast_project) 19s -> 34s

- select \`weather_forecast_project\` in \`PROJECT\`
- frame the forecast as a constraint signal for the decision engine
- present this as model selection / prediction, not a standalone weather demo
- show only the minimal prediction context:
  - station
  - lag / horizon
- move to \`ORCHESTRATE\` and show one runnable backtest / forecast action
- flash \`WORKFLOW\` long enough to prove replayable feature / forecast steps
- finish on \`ANALYSIS\` with:
  - one metrics card cluster
  - one observed-vs-predicted curve
- do not linger on extra tabs once the metrics frame is readable

### Act 3: Distributed optimization and decision ($RL_APP_LABEL) 34s -> 55s

- switch to \`$RL_APP_LABEL\`
- show one routing or optimization choice only:
  - \`queue_aware\`
  - or \`shortest_path\` baseline comparison
  - \`PPO-GNN\`
  - or \`Path Actor-Critic\`
- move to \`ORCHESTRATE\` and show visible worker / cluster activity
- make this the key moment in the cut
- if a non-local worker is used, make the shared workers data path visible and avoid local-only paths
- flash \`WORKFLOW\` only if replayable optimization or inference steps are already visible
- finish on one visible decision proof:
  - selected route
  - trained policy artifact
  - or exported routing result
  - or routing-analysis evidence
- if live training is too slow, keep the final artifact frame and cut the rest

### Act 4: Failure injection and adaptation 55s -> 66s

- inject or reveal one operational change:
  - bandwidth drop
  - node failure
  - risk increase
- show the system response:
  - recompute
  - re-optimize
  - new route / decision
- keep this short; the audience only needs to see the before/after decision change

### Closing synthesis: 66s -> 74s

- end on the decision and metrics:
  - latency down
  - cost down
  - reliability up
- closing sentence:
  - \`This is not a model. This is an autonomous system path from mission data to decision.\`
- keep the closing frame static and short

## Technical stack callouts

- \`AgiEnv\`: environment orchestration
- \`AgiNode / AgiCluster\`: distributed execution
- \`Dask / worker execution\`: parallel computing path when enabled
- ML + optimization / RL: decision loop
- Streamlit: operator visualization

## Optional add-on

Air-gapped mode:

- no internet access
- local models only
- use this only when the environment is configured and validated

## Winning criteria

| Criteria | Strength |
|---|---|
| Innovation | Autonomous pipeline path |
| Scalability | Distributed worker execution |
| Real use case | Mission / network optimization |
| AI depth | ML + optimization / orchestration |
| Differentiation | Not a chatbot |

## Recording constraints

- target one page transition per act, not a full tour
- each act must end on evidence, not only on settings
- do not spend time on install details
- do not branch into alternative apps inside an act
- do not wait for long-running steps on screen; cut to the prepared evidence frame
- use hard cuts between acts rather than animated panning
- if an act needs more than two visible settings, it is too slow
- keep dynamic-pipeline claims grounded in visible AGILAB steps, generated snippets, and replayable evidence
- if the decision act becomes too heavy, keep:
  - optimizer selection
  - one run snippet or worker activity frame
  - one final decision / evidence frame
EOF

echo "Cue sheet written:"
echo "  $PLAN_FILE"
echo
echo "Project roots:"
echo "  data: $DATA_APP_ROOT"
echo "  ml:   $ML_APP_ROOT"
echo "  rl:   $RL_APP_ROOT"
echo

if [[ ! -d "$RL_APP_ROOT" ]]; then
  echo "Note: decision act root does not exist yet. Pass --rl-app-root to use a local routing/optimization app."
  echo
fi

CMD=("$ROOT/tools/capture_demo_workflow.sh" --name "$NAME" --duration "$DURATION" --start "$START")

if [[ -n "$TRIM" ]]; then
  CMD+=(--trim "$TRIM")
fi

if [[ -n "$CROP" ]]; then
  CMD+=(--crop "$CROP")
fi

if [[ "$VIA_TERMINAL" == "1" ]]; then
  CMD+=(--via-terminal)
fi

echo "Capture command:"
printf '  %q' "${CMD[@]}"
printf '\n'

if [[ "$PRINT_ONLY" == "1" ]]; then
  exit 0
fi

echo
echo "Open the cue sheet before recording, then follow the act sequence."
"${CMD[@]}"
