#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  cat <<'EOF'
Usage:
  tools/capture_three_project_demo.sh [--name demo-name] [--duration 82] [--start 0] [--trim 74] [--crop x:y:w:h] [--rl-app-root /path/to/sb3_trainer_project] [--print-only] [--via-terminal]

What it does:
  1. Writes a concrete cue sheet for a technical AGILAB demo covering data, ML, and RL.
  2. Points the operator to the exact project roots used for each act.
  3. Delegates the actual recording/export to tools/capture_demo_workflow.sh.

Default acts:
  - Data: execution_pandas_project
  - ML: meteo_forecast_project
  - RL: sb3_trainer_project (from the sibling thales_agilab apps repo)

Examples:
  tools/capture_three_project_demo.sh
  tools/capture_three_project_demo.sh --name agilab-data-ml-rl --duration 82 --trim 74
  tools/capture_three_project_demo.sh --name agilab-data-ml-rl --duration 82 --trim 74 --via-terminal
  tools/capture_three_project_demo.sh --print-only
EOF
  exit 0
fi

NAME="agilab-data-ml-rl"
DURATION="82"
START="0"
TRIM="74"
CROP=""
PRINT_ONLY="0"
RL_APP_ROOT=""
VIA_TERMINAL="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name)
      NAME="$2"
      shift 2
      ;;
    --duration)
      DURATION="$2"
      shift 2
      ;;
    --start)
      START="$2"
      shift 2
      ;;
    --trim)
      TRIM="$2"
      shift 2
      ;;
    --crop)
      CROP="$2"
      shift 2
      ;;
    --rl-app-root)
      RL_APP_ROOT="$2"
      shift 2
      ;;
    --print-only)
      PRINT_ONLY="1"
      shift
      ;;
    --via-terminal)
      VIA_TERMINAL="1"
      shift
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 2
      ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_RL_APP_ROOT="$ROOT/../thales_agilab/apps/sb3_trainer_project"
if [[ -z "$RL_APP_ROOT" ]]; then
  RL_APP_ROOT="$DEFAULT_RL_APP_ROOT"
fi

DATA_APP_ROOT="$ROOT/src/agilab/apps/builtin/execution_pandas_project"
ML_APP_ROOT="$ROOT/src/agilab/apps/builtin/meteo_forecast_project"

OUT_DIR="$ROOT/artifacts/demo_media/$NAME"
mkdir -p "$OUT_DIR"
PLAN_FILE="$OUT_DIR/${NAME}_cue_sheet.md"

cat > "$PLAN_FILE" <<EOF
# AGILAB Technical Hero Demo Cue Sheet

This cue sheet is generated by \`tools/capture_three_project_demo.sh\`.

Preferred cut: \`70-75s\` final runtime with hard transitions and no idle waiting.

## Goal

Show that AGILAB can support three concrete workflow types in one coherent shell:

- data workflow
- ML workflow
- RL workflow

## Recording settings

- clip name: \`$NAME\`
- raw duration target: \`$DURATION\` seconds
- edited duration target: \`$TRIM\` seconds
- trim start: \`$START\` seconds
- crop: \`${CROP:-none}\`

## Project roots

- data act: \`$DATA_APP_ROOT\`
- ML act: \`$ML_APP_ROOT\`
- RL act: \`$RL_APP_ROOT\`

## Timeline

### Intro: 0s -> 3s

- open AGILAB
- show one opener line only:
  - \`DATA -> ML -> RL in one reproducible shell\`

### Act 1: Data workflow (execution_pandas_project) 3s -> 21s

- select \`execution_pandas_project\` in \`PROJECT\`
- show only the highest-signal data settings:
  - \`nfile\`
  - \`rows_per_file\`
- move immediately to \`ORCHESTRATE\` and show one runnable compute step
- flash \`PIPELINE\` only long enough to prove replayable steps exist
- finish on one concrete proof frame:
  - generated dataset artifact
  - or exported compute result
- cut as soon as the evidence is visible

### Act 2: ML workflow (meteo_forecast_project) 21s -> 42s

- select \`meteo_forecast_project\` in \`PROJECT\`
- show only the minimal forecasting context:
  - station
  - lag / horizon
- move to \`ORCHESTRATE\` and show one runnable backtest / forecast action
- flash \`PIPELINE\` long enough to prove replayable forecast steps
- finish on \`ANALYSIS\` with:
  - one metrics card cluster
  - one observed-vs-predicted curve
- do not linger on extra tabs once the metrics frame is readable

### Act 3: RL workflow (sb3_trainer_project) 42s -> 64s

- switch to \`sb3_trainer_project\`
- show one real trainer choice only:
  - \`PPO-GNN\`
  - or \`Path Actor-Critic\`
- move to \`ORCHESTRATE\` and show one training run entry
- flash \`PIPELINE\` only if replayable training or inference steps are already visible
- finish on one visible RL proof:
  - trained policy artifact
  - or exported routing result
  - or routing-analysis evidence
- if training visuals are too slow, keep the final artifact frame and cut the rest

### Closing synthesis: 64s -> 72s

- end on one sentence:
  - \`One reproducible workflow shell for data, ML, and RL.\`
- keep the closing frame static and short

## Recording constraints

- target one page transition per act, not a full tour
- each act must end on evidence, not only on settings
- do not spend time on install details
- do not branch into alternative apps inside an act
- do not wait for long-running steps on screen; cut to the prepared evidence frame
- use hard cuts between acts rather than animated panning
- if an act needs more than two visible settings, it is too slow
- if the RL act becomes too heavy, keep:
  - trainer selection
  - one run snippet
  - one final artifact / evidence frame
EOF

echo "Cue sheet written:"
echo "  $PLAN_FILE"
echo
echo "Project roots:"
echo "  data: $DATA_APP_ROOT"
echo "  ml:   $ML_APP_ROOT"
echo "  rl:   $RL_APP_ROOT"
echo

CMD=("$ROOT/tools/capture_demo_workflow.sh" --name "$NAME" --duration "$DURATION" --start "$START")

if [[ -n "$TRIM" ]]; then
  CMD+=(--trim "$TRIM")
fi

if [[ -n "$CROP" ]]; then
  CMD+=(--crop "$CROP")
fi

if [[ "$VIA_TERMINAL" == "1" ]]; then
  CMD+=(--via-terminal)
fi

echo "Capture command:"
printf '  %q' "${CMD[@]}"
printf '\n'

if [[ "$PRINT_ONLY" == "1" ]]; then
  exit 0
fi

echo
echo "Open the cue sheet before recording, then follow the act sequence."
"${CMD[@]}"
