#!/usr/bin/env python3
"""Generate public documentation license inventories from the package split."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Iterable, Sequence


ROOT = Path(__file__).resolve().parents[1]
TOOLS_ROOT = ROOT / "tools"
if str(TOOLS_ROOT) not in sys.path:
    sys.path.insert(0, str(TOOLS_ROOT))

from package_split_contract import PACKAGE_CONTRACTS, PackageContract, project_path, pyproject_path  # noqa: E402


LOCAL_PACKAGE_LICENSE = "BSD-3-Clause"
LOCAL_PACKAGE_LICENSES = {package.name: LOCAL_PACKAGE_LICENSE for package in PACKAGE_CONTRACTS}
LOCAL_PACKAGE_PREFIXES = ("agi-", "agilab")
GENERATED_MARKER = "Generated by `tools/generate_docs_license_inventories.py`."
LICENSE_FILE_SUFFIX = "-licenses.md"
SNAPSHOT_START = "<!-- AGILAB_LICENSE_SNAPSHOT_START -->"
SNAPSHOT_END = "<!-- AGILAB_LICENSE_SNAPSHOT_END -->"
REVIEW_LICENSE_TOKENS = ("AGPL", "GPL", "LGPL", "EPL", "MPL", "CDDL")
SKIPPED_MANIFEST_DIRS = {".venv", "build", "dist", "__pycache__"}
LICENSECHECK_COMPAT_SCRIPT = """
from license_expression import LicenseWithExceptionSymbol

if not hasattr(LicenseWithExceptionSymbol, "key"):
    LicenseWithExceptionSymbol.key = property(
        lambda self: f"{self.license_symbol.key} WITH {self.exception_symbol.key}"
    )

from importlib.metadata import distribution

command = next(
    entry for entry in distribution("licensecheck").entry_points
    if entry.group == "console_scripts" and entry.name == "licensecheck"
)
raise SystemExit(command.load()())
"""


@dataclass(frozen=True)
class InventorySpec:
    package: PackageContract
    manifests: tuple[Path, ...]
    extras: tuple[str, ...] = ()

    @property
    def docname(self) -> str:
        return f"{self.package.name}-licenses"

    @property
    def output_name(self) -> str:
        return f"{self.docname}.md"


SECTION_DEFINITIONS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Top-level package", ("top-level-bundle",)),
    ("Runtime packages", ("runtime-component", "runtime-bundle")),
    ("UI and page packages", ("ui-component", "page-bundle", "page-umbrella")),
    ("App packages", ("app-project", "app-compatibility", "app-umbrella")),
)


def _load_pyproject(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def _root_extras() -> tuple[str, ...]:
    data = _load_pyproject(ROOT / "pyproject.toml")
    optional = data.get("project", {}).get("optional-dependencies", {})
    return tuple(sorted(optional))


def _is_skipped_manifest(path: Path) -> bool:
    return any(part in SKIPPED_MANIFEST_DIRS for part in path.parts)


def _embedded_manifests(package: PackageContract) -> tuple[Path, ...]:
    base = pyproject_path(ROOT, package)
    manifests = [base]
    if package.role == "app-project":
        root = project_path(ROOT, package)
        manifests.extend(
            path
            for path in sorted(root.rglob("pyproject.toml"))
            if path != base and not _is_skipped_manifest(path)
        )
    return tuple(dict.fromkeys(manifests))


def inventory_specs(repo_root: Path = ROOT) -> tuple[InventorySpec, ...]:
    del repo_root  # The package split contract is anchored at the active repo root.
    specs: list[InventorySpec] = []
    for package in PACKAGE_CONTRACTS:
        extras = _root_extras() if package.role == "top-level-bundle" else ()
        specs.append(InventorySpec(package=package, manifests=_embedded_manifests(package), extras=extras))
    return tuple(specs)


def _run_licensecheck(spec: InventorySpec) -> dict:
    cmd = [
        "uv",
        "--preview-features",
        "extra-build-dependencies",
        "run",
        "--with",
        "licensecheck",
        "python",
        "-c",
        LICENSECHECK_COMPAT_SCRIPT,
        "--format",
        "json",
        "--requirements-paths",
        *(str(path) for path in spec.manifests),
    ]
    if spec.extras:
        cmd.extend(["--extras", *spec.extras])

    completed = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True, check=False)
    if completed.returncode:
        raise RuntimeError(
            "licensecheck failed for "
            f"{spec.package.name} with exit code {completed.returncode}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        )
    try:
        return json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"licensecheck produced invalid JSON for {spec.package.name}\n"
            f"stdout:\n{completed.stdout}\n"
            f"stderr:\n{completed.stderr}"
        ) from exc


def _normalize_license(name: str, license_text: str) -> str:
    normalized = license_text.strip()
    if name in LOCAL_PACKAGE_LICENSES:
        return LOCAL_PACKAGE_LICENSES[name]
    return normalized or "UNKNOWN"


def _is_unexpected_local_package(name: str) -> bool:
    normalized = name.lower()
    return normalized not in LOCAL_PACKAGE_LICENSES and normalized.startswith(LOCAL_PACKAGE_PREFIXES)


def _merge_packages(packages: Iterable[dict]) -> list[dict[str, str]]:
    merged: dict[str, dict[str, set[str]]] = {}
    for package in packages:
        name = str(package.get("name", "")).strip()
        if not name:
            continue
        if _is_unexpected_local_package(name):
            continue
        version = str(package.get("version", "")).strip() or "UNKNOWN"
        license_text = _normalize_license(name, str(package.get("license", "")))
        entry = merged.setdefault(name, {"versions": set(), "licenses": set()})
        entry["versions"].add(version)
        entry["licenses"].add(license_text)

    rows: list[dict[str, str]] = []
    for name, values in sorted(merged.items(), key=lambda item: item[0].lower()):
        rows.append(
            {
                "name": name,
                "version": "<br>".join(sorted(values["versions"])),
                "license": "<br>".join(sorted(values["licenses"])),
            }
        )
    return rows


def _has_review_license(license_text: str) -> bool:
    upper = license_text.upper()
    return any(token in upper for token in REVIEW_LICENSE_TOKENS)


def _md_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def _relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def render_inventory(spec: InventorySpec, licensecheck_output: dict) -> str:
    rows = _merge_packages(licensecheck_output.get("packages", []))
    flagged = [row["name"] for row in rows if _has_review_license(row["license"])]
    version = licensecheck_output.get("info", {}).get("version", "unknown")
    manifests = "\n".join(f"- `{_relative(path)}`" for path in spec.manifests)
    extras = ", ".join(f"`{extra}`" for extra in spec.extras) if spec.extras else "none"
    flag_text = (
        ", ".join(f"`{name}`" for name in flagged)
        if flagged
        else "No GPL/LGPL/EPL/MPL/CDDL-style license strings detected."
    )

    lines = [
        f"# `{spec.package.name}` License Inventory",
        "",
        GENERATED_MARKER,
        f"Source package role: `{spec.package.role}`.",
        f"Resolver: `licensecheck {version}`.",
        "",
        "Source manifests:",
        manifests,
        "",
        f"Extras included: {extras}.",
        "",
        "Audit notes:",
        "- This page lists Python dependency metadata resolved for documentation review.",
        "- AGILAB-owned packages are normalized to `BSD-3-Clause` when PyPI metadata is incomplete.",
        "- Dependency metadata can be broader than vendored source; review redistribution changes separately.",
        f"- Review flags: {flag_text}",
        "",
        "| Package Name | Version | License |",
        "|--------------|---------|---------|",
    ]
    lines.extend(
        f"| {_md_cell(row['name'])} | {_md_cell(row['version'])} | {_md_cell(row['license'])} |"
        for row in rows
    )
    lines.append("")
    return "\n".join(lines)


def retain_inventory_snapshot(text: str, retained_on: date) -> str:
    """Label an existing generated report without resolving or changing its rows."""
    table_header = "| Package Name | Version | License |"
    if text.count(GENERATED_MARKER) != 1 or text.count(table_header) != 1:
        raise ValueError("Cannot retain an unrecognized generated license inventory.")
    original_table = text[text.index(table_header):]
    if SNAPSHOT_START in text or SNAPSHOT_END in text:
        if text.count(SNAPSHOT_START) != 1 or text.count(SNAPSHOT_END) != 1:
            raise ValueError("Malformed license snapshot markers.")
        before, rest = text.split(SNAPSHOT_START, 1)
        _, after = rest.split(SNAPSHOT_END, 1)
        text = before + after.lstrip("\n")
    notice = "\n".join(
        [
            SNAPSHOT_START,
            f"**Historical dependency metadata snapshot retained on {retained_on.isoformat()}.**",
            "Original acquisition date and manifest revisions were not recorded.",
            "This report may include legacy environments and does not describe current native source dependencies.",
            "The package manifest locations below are identifiers, not verified provenance of the original report.",
            "Package versions, license strings and table rows are preserved without re-resolution.",
            SNAPSHOT_END,
            "",
            "",
        ]
    )
    text = text.replace(GENERATED_MARKER, notice + GENERATED_MARKER, 1)
    text = text.replace("Source manifests:\n", "Package manifest locations:\n", 1)
    if table_header not in text or text[text.index(table_header):] != original_table:
        raise ValueError("Snapshot markers or manifest labels must not change the dependency table.")
    return text


def _read_snapshot_report(path: Path) -> str:
    if path.is_symlink():
        raise ValueError(f"Snapshot inventories must be real files: {path}")
    return path.read_text(encoding="utf-8")


def _specs_by_section(specs: Sequence[InventorySpec]) -> list[tuple[str, list[InventorySpec]]]:
    sections: list[tuple[str, list[InventorySpec]]] = []
    for title, roles in SECTION_DEFINITIONS:
        selected = [spec for spec in specs if spec.package.role in roles]
        if selected:
            sections.append((title, selected))
    return sections


def render_license_index(
    specs: Sequence[InventorySpec], *, retained_on: date | None = None,
    historical_docnames: Sequence[str] = (),
) -> str:
    lines = [
        "Licenses",
        "========",
        "",
        "There are three distinct license scopes to keep in mind when reading this documentation:",
        "",
        "- **AGILab source code license**: defined by the repository root ``LICENSE`` and attributions in ``NOTICE``.",
        "- **Vendored third-party assets**: copied source or assets carry attribution under ``LICENSES/`` when required.",
        "- **Python dependency inventories**: the generated pages below list package metadata resolved from the public package split.",
        "",
        "The dependency inventories are generated with ``tools/generate_docs_license_inventories.py`` from",
        "``tools/package_split_contract.py`` and the relevant ``pyproject.toml`` files. They are audit aids, not",
        "a substitute for legal review before changing redistribution scope.",
        "",
        "Review notes",
        "------------",
        "",
        "- AGILAB-owned distributions are normalized to ``BSD-3-Clause`` when external package metadata is incomplete.",
        "- GPL/LGPL/EPL/MPL/CDDL-style strings are surfaced as review flags on the generated pages.",
        "- Runtime and transitive dependencies can appear here even when no source is vendored in this repository.",
        "",
        "Vendored third-party assets",
        "---------------------------",
        "",
        "The dependency inventories do not replace vendored attribution. Current vendored attribution includes",
        "``LICENSES/LICENSE-MIT-barviz-mod`` for the adapted barycentric visualization code used by",
        "``agi-page-simplex-map``.",
        "",
    ]

    if retained_on is not None:
        description = "- **Python dependency inventories**: the generated pages below list package metadata resolved from the public package split."
        lines[lines.index(description)] = "- **Historical Python dependency snapshots**: retained metadata reports; these are not current native dependency graphs."
        paragraph_start = lines.index(
            "The dependency inventories are generated with ``tools/generate_docs_license_inventories.py`` from"
        )
        lines[paragraph_start:paragraph_start + 3] = [
            f"The dependency metadata snapshots were retained on {retained_on.isoformat()} with",
            f"``tools/generate_docs_license_inventories.py --preserve-existing-snapshot {retained_on.isoformat()}``.",
            "Original acquisition dates and manifest revisions were not recorded; snapshots may include legacy environments.",
            "Their package manifest locations come from reports based on ``tools/package_split_contract.py``;",
            "they do not establish the original manifest revisions or describe current native source dependencies.",
            "A current resolved license inventory for the native source is not available here.",
            "Consult the current source manifests for declared dependencies; these snapshots remain audit aids,",
            "not a substitute for legal review before changing redistribution scope.",
        ]

    for title, section_specs in _specs_by_section(specs):
        lines.extend(
            [
                title,
                "-" * len(title),
                "",
                ".. toctree::",
                "   :maxdepth: 1",
                f"   :caption: {title}",
                "",
            ]
        )
        lines.extend(f"   {spec.package.name} <{spec.docname}>" for spec in section_specs)
        lines.append("")

    if historical_docnames:
        lines.extend([
            "Additional historical snapshots",
            "-------------------------------",
            "",
            "These reports are retained even though their packages are absent from the current package split.",
            "",
            ".. toctree::",
            "   :maxdepth: 1",
            "",
            *(f"   {docname}" for docname in historical_docnames),
            "",
        ])

    return "\n".join(lines)


def _write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def _stale_generated_license_files(docs_source: Path, expected_names: set[str]) -> list[Path]:
    stale: list[Path] = []
    for path in sorted(docs_source.glob(f"*{LICENSE_FILE_SUFFIX}")):
        if path.name in expected_names:
            continue
        text = path.read_text(encoding="utf-8")
        if "generated inventory" in text.lower() or GENERATED_MARKER in text:
            stale.append(path)
    return stale


def generate(
    docs_source: Path, *, check: bool = False, retained_on: date | None = None
) -> int:
    if retained_on is None:
        docs_source.mkdir(parents=True, exist_ok=True)
    elif docs_source.is_symlink():
        raise ValueError("Snapshot docs source must be a real directory.")
    elif not docs_source.is_dir():
        raise FileNotFoundError(docs_source)
    specs = inventory_specs(ROOT)
    expected: dict[Path, str] = {}
    for spec in specs:
        output = docs_source / spec.output_name
        if retained_on is not None:
            expected[output] = retain_inventory_snapshot(_read_snapshot_report(output), retained_on)
        else:
            expected[output] = render_inventory(spec, _run_licensecheck(spec))

    historical_docnames: list[str] = []
    if retained_on is not None:
        for output in sorted(docs_source.glob(f"*{LICENSE_FILE_SUFFIX}")):
            if output in expected:
                continue
            text = _read_snapshot_report(output)
            if GENERATED_MARKER in text:
                expected[output] = retain_inventory_snapshot(text, retained_on)
                historical_docnames.append(output.stem)
            elif "generated inventory" in text.lower():
                raise ValueError(f"Cannot retain an unrecognized generated license inventory: {output}")
    index_path = docs_source / "license.rst"
    if retained_on is not None and index_path.is_symlink():
        raise ValueError("Snapshot license index must be a real file.")
    expected[index_path] = render_license_index(
        specs, retained_on=retained_on, historical_docnames=historical_docnames
    )

    expected_names = {path.name for path in expected if path.name.endswith(LICENSE_FILE_SUFFIX)}
    stale_files = [] if retained_on is not None else _stale_generated_license_files(docs_source, expected_names)

    changed: list[str] = []
    for path, content in expected.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        changed.append(path.relative_to(docs_source).as_posix())
        if not check:
            path.write_text(content, encoding="utf-8")

    for path in stale_files:
        changed.append(path.relative_to(docs_source).as_posix())
        if not check:
            path.unlink()

    if changed:
        action = "would update" if check else "updated"
        for relpath in sorted(changed):
            print(f"{action}: {relpath}")
        return 1 if check else 0

    print("license inventories up to date")
    return 0


def _default_docs_source() -> Path:
    canonical = ROOT.parent / "thales_agilab" / "docs" / "source"
    return canonical if canonical.exists() else ROOT / "docs" / "source"


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docs-source",
        type=Path,
        default=_default_docs_source(),
        help="Docs source directory to update. Defaults to the sibling canonical docs source when present.",
    )
    parser.add_argument("--check", action="store_true", help="Fail if generated files would change.")
    parser.add_argument(
        "--preserve-existing-snapshot",
        type=date.fromisoformat,
        metavar="YYYY-MM-DD",
        help="Retain existing generated dependency tables with an explicit historical snapshot notice; no dependency resolution.",
    )
    args = parser.parse_args(argv)
    docs_source = (
        args.docs_source.absolute() if args.preserve_existing_snapshot else args.docs_source.resolve()
    )
    return generate(
        docs_source, check=args.check, retained_on=args.preserve_existing_snapshot
    )


if __name__ == "__main__":
    raise SystemExit(main())
