#!/usr/bin/env python3
"""Create and validate AGILAB parallel-stage contracts.

This tool does not run distributed workers. It captures the user-facing
parallelization intent in a small TOML contract that an app, notebook, or
WORKFLOW stage can consume: function + split rule + reducer.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence


SCHEMA = "agilab.parallel_stage.v1"
SPLIT_MODES = ("files", "data-partitions", "parameter-sweep")
BACKENDS = ("local", "pool", "dask")
REDUCERS = ("collect-json", "concat-jsonl", "concat-csv", "custom")
PARTITION_STRATEGIES = (
    "one-file-per-partition",
    "file-chunks",
    "row-chunks",
    "parameter-items",
)
FUNCTION_PATTERN = re.compile(r"^[A-Za-z0-9_./:-]+:[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True)
class ParallelStageContract:
    schema: str
    name: str
    function: str
    split: str
    input: str
    workers: int | str
    partition_strategy: str
    target_partitions: int
    min_partitions_per_worker: int
    reducer: str
    backend: str
    output: str
    notes: str = ""


@dataclass(frozen=True)
class ValidationResult:
    ok: bool
    issues: tuple[str, ...]
    warnings: tuple[str, ...] = ()


def _toml_string(value: str) -> str:
    return json.dumps(value)


def render_contract(contract: ParallelStageContract) -> str:
    rows = [
        "# Generated by tools/parallel_stage.py.",
        "# Contract: function + split rule + reducer = parallel AGILAB stage.",
        f"schema = {_toml_string(contract.schema)}",
        f"name = {_toml_string(contract.name)}",
        f"function = {_toml_string(contract.function)}",
        f"split = {_toml_string(contract.split)}",
        f"input = {_toml_string(contract.input)}",
        f"workers = {_toml_value(contract.workers)}",
        f"partition_strategy = {_toml_string(contract.partition_strategy)}",
        f"target_partitions = {contract.target_partitions}",
        f"min_partitions_per_worker = {contract.min_partitions_per_worker}",
        f"reducer = {_toml_string(contract.reducer)}",
        f"backend = {_toml_string(contract.backend)}",
        f"output = {_toml_string(contract.output)}",
    ]
    if contract.notes:
        rows.append(f"notes = {_toml_string(contract.notes)}")
    rows.extend(
        [
            "",
            "[next_steps]",
            "local_preview = \"Run the function against one partition before scaling.\"",
            "workflow_stage = \"Import this contract from a WORKFLOW stage or app run method.\"",
            "distributed_run = \"Switch backend to dask only after local preview passes.\"",
            "evidence = \"Write partition outputs and reducer output under the run manifest directory.\"",
        ]
    )
    return "\n".join(rows) + "\n"


def build_contract(
    *,
    name: str,
    function: str,
    split: str,
    input_value: str,
    workers: int | str,
    reducer: str,
    backend: str,
    output: str,
    partition_strategy: str = "one-file-per-partition",
    target_partitions: int = 0,
    min_partitions_per_worker: int = 2,
    notes: str = "",
) -> ParallelStageContract:
    return ParallelStageContract(
        schema=SCHEMA,
        name=name,
        function=function,
        split=split,
        input=input_value,
        workers=workers,
        partition_strategy=partition_strategy,
        target_partitions=target_partitions,
        min_partitions_per_worker=min_partitions_per_worker,
        reducer=reducer,
        backend=backend,
        output=output,
        notes=notes,
    )


def _toml_value(value: int | str) -> str:
    if isinstance(value, int):
        return str(value)
    return _toml_string(value)


def recommended_effective_workers(
    *,
    file_count: int,
    workers: int | str,
    files_are_splittable: bool,
) -> int | str:
    """Return the worker count policy for file-based stages.

    When there are fewer files than cores, the useful worker count is bounded by
    the number of independent partitions. Splittable files should create more
    partitions; unsplittable files should cap workers to file count.
    """

    if workers == "auto":
        return "auto"
    if workers < 1:
        raise ValueError("workers must be positive or 'auto'")
    if file_count < 1:
        return 1
    if file_count >= workers:
        return workers
    if files_are_splittable:
        return workers
    return file_count


def validate_mapping(data: Mapping[str, Any]) -> ValidationResult:
    issues: list[str] = []
    warnings: list[str] = []

    required = (
        "schema",
        "name",
        "function",
        "split",
        "input",
        "workers",
        "partition_strategy",
        "target_partitions",
        "min_partitions_per_worker",
        "reducer",
        "backend",
        "output",
    )
    for key in required:
        if key not in data:
            issues.append(f"missing required key: {key}")

    if data.get("schema") != SCHEMA:
        issues.append(f"schema must be {SCHEMA!r}")

    name = data.get("name")
    if not isinstance(name, str) or not name.strip():
        issues.append("name must be a non-empty string")

    function = data.get("function")
    if not isinstance(function, str) or not FUNCTION_PATTERN.match(function):
        issues.append("function must use 'module_or_path:function_name' format")

    split = data.get("split")
    if split not in SPLIT_MODES:
        issues.append(f"split must be one of: {', '.join(SPLIT_MODES)}")

    input_value = data.get("input")
    if not isinstance(input_value, str) or not input_value.strip():
        issues.append("input must be a non-empty string")

    workers = data.get("workers")
    if workers != "auto" and (not isinstance(workers, int) or workers < 1):
        issues.append("workers must be a positive integer or 'auto'")
    elif workers == 1:
        warnings.append("workers=1 is valid for preview but does not parallelize execution")

    partition_strategy = data.get("partition_strategy")
    if partition_strategy not in PARTITION_STRATEGIES:
        issues.append(f"partition_strategy must be one of: {', '.join(PARTITION_STRATEGIES)}")

    target_partitions = data.get("target_partitions")
    if not isinstance(target_partitions, int) or target_partitions < 0:
        issues.append("target_partitions must be a non-negative integer")

    min_partitions_per_worker = data.get("min_partitions_per_worker")
    if not isinstance(min_partitions_per_worker, int) or min_partitions_per_worker < 1:
        issues.append("min_partitions_per_worker must be a positive integer")

    if split == "files" and workers != "auto" and isinstance(workers, int):
        if partition_strategy == "one-file-per-partition":
            warnings.append(
                "if file count is lower than workers, one-file-per-partition caps useful parallelism at file count"
            )
        elif partition_strategy == "file-chunks" and target_partitions == 0:
            warnings.append("file-chunks should set target_partitions to over-partition large files")

    reducer = data.get("reducer")
    if reducer not in REDUCERS:
        issues.append(f"reducer must be one of: {', '.join(REDUCERS)}")

    backend = data.get("backend")
    if backend not in BACKENDS:
        issues.append(f"backend must be one of: {', '.join(BACKENDS)}")

    output = data.get("output")
    if not isinstance(output, str) or not output.strip():
        issues.append("output must be a non-empty string")

    if reducer == "custom" and "notes" not in data:
        warnings.append("custom reducer should describe the merge contract in notes")

    if backend == "dask" and workers == 1:
        warnings.append("dask backend normally needs more than one worker to be useful")

    return ValidationResult(ok=not issues, issues=tuple(issues), warnings=tuple(warnings))


def load_contract(path: Path) -> Mapping[str, Any]:
    with path.open("rb") as handle:
        data = tomllib.load(handle)
    return data


def write_contract(path: Path, contract: ParallelStageContract) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_contract(contract), encoding="utf-8")


def _summary(path: Path, result: ValidationResult) -> str:
    lines = [f"parallel stage contract: {path}"]
    lines.append("status: ok" if result.ok else "status: invalid")
    for issue in result.issues:
        lines.append(f"issue: {issue}")
    for warning in result.warnings:
        lines.append(f"warning: {warning}")
    return "\n".join(lines)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", type=Path, help="Validate an existing parallel_stage.toml file.")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    parser.add_argument("--output", type=Path, default=Path("parallel_stage.toml"), help="Output TOML path.")
    parser.add_argument("--name", help="Parallel stage name.")
    parser.add_argument("--function", help="Function in module_or_path:function_name format.")
    parser.add_argument("--split", choices=SPLIT_MODES, help="Work partitioning strategy.")
    parser.add_argument("--input", dest="input_value", help="Input glob, table path, or parameter-grid file.")
    parser.add_argument("--workers", type=int, default=2, help="Desired worker count.")
    parser.add_argument(
        "--workers-auto",
        action="store_true",
        help="Record workers = 'auto' so the runner can cap or scale from available partitions.",
    )
    parser.add_argument(
        "--partition-strategy",
        choices=PARTITION_STRATEGIES,
        default="one-file-per-partition",
        help="How to create partitions when inputs and workers do not match.",
    )
    parser.add_argument(
        "--target-partitions",
        type=int,
        default=0,
        help="Desired partition count; 0 means leave it to the runner.",
    )
    parser.add_argument(
        "--min-partitions-per-worker",
        type=int,
        default=2,
        help="Preferred minimum partitions per worker for load balancing.",
    )
    parser.add_argument("--reducer", choices=REDUCERS, default="collect-json", help="Reducer contract.")
    parser.add_argument("--backend", choices=BACKENDS, default="local", help="Execution backend.")
    parser.add_argument("--notes", default="", help="Optional human-readable contract note.")
    return parser


def _missing_generate_args(args: argparse.Namespace) -> tuple[str, ...]:
    missing = []
    for key in ("name", "function", "split", "input_value"):
        if not getattr(args, key):
            missing.append("--" + key.replace("_value", "").replace("_", "-"))
    return tuple(missing)


def main(argv: Sequence[str] | None = None) -> int:
    parser = _parser()
    args = parser.parse_args(argv)

    if args.check:
        result = validate_mapping(load_contract(args.check))
        if args.json:
            print(json.dumps({"path": str(args.check), **asdict(result)}, indent=2, sort_keys=True))
        else:
            print(_summary(args.check, result))
        return 0 if result.ok else 1

    missing = _missing_generate_args(args)
    if missing:
        parser.error("missing required generation arguments: " + ", ".join(missing))

    contract = build_contract(
        name=args.name,
        function=args.function,
        split=args.split,
        input_value=args.input_value,
        workers="auto" if args.workers_auto else args.workers,
        partition_strategy=args.partition_strategy,
        target_partitions=args.target_partitions,
        min_partitions_per_worker=args.min_partitions_per_worker,
        reducer=args.reducer,
        backend=args.backend,
        output=str(args.output),
        notes=args.notes,
    )
    result = validate_mapping(asdict(contract))
    if not result.ok:
        if args.json:
            print(json.dumps({"path": str(args.output), **asdict(result)}, indent=2, sort_keys=True))
        else:
            print(_summary(args.output, result), file=sys.stderr)
        return 1

    write_contract(args.output, contract)
    if args.json:
        print(json.dumps({"path": str(args.output), "contract": asdict(contract), **asdict(result)}, indent=2, sort_keys=True))
    else:
        print(_summary(args.output, result))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
