[project]
name = "ilp_project"
version = "0.8.17"
description = "ILP routing demo packaged as an AGILab app"
requires-python = ">=3.11"
readme = "README.md"
authors = [
    { name = "AGILab Team" }
]

dependencies = [
    "gymnasium",
    "build",
    "humanize",
    "matplotlib",
    "networkx",
    "numpy",
    "pulp",
    "pydantic",
    "streamlit",
]

[project.license]
text = "Thales SIX GTS France SAS"

[dependency-groups]
dev = [
    "black",
    "pytest",
    "pytest-cov",
    "pytest-local-badge",
    "pytest-asyncio",
    "licensecheck",
    "ilp_project",
]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.sources.ilp_project]
workspace = true

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
ilp_project = [
    "**/*.json",
    "**/*.toml",
    "**/*.txt",
]

[tool.pytest.ini_options]
testpaths = ["test"]
asyncio_mode = "auto"
filterwarnings = [
    "ignore:.*Gymnasium.*:UserWarning",
]
