[project]
name = "view-maps-3d"
version = "0.8.17"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.5.0",
    "streamlit>=1.49.1",
    "watchdog>=6.0.0",
    "agi-env",
    "plotly>=6.3.0",
    "sqlalchemy>=2.0.43",
    "geojson>=3.2.0",
]

[tool.uv.sources.agi-env]
path = "../../core/agi-env"
editable = true

