name: no-symlinks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if symlinks are present in repo
        run: |
          set -e
          if git ls-files -s | awk '$1 ~ /^120000/ {print $4}'; then
            echo "Symlinks detected in repository. Please remove them." >&2
            exit 1
          fi
