name: Upload release to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the release'
        required: true

  push:
    tags:
      - 'v*.*.*'

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install uv

    - name: Remove the main dist directory
      run: rm -rf dist

    - name: Update version in pyproject.toml
      env:
        VERSION: ${{ github.event.inputs.version || github.ref_name }}
      run: |
        VERSION=${VERSION#v}
        echo "Setting version: $VERSION"
        sed -i "s/^version = .*/version = \"$VERSION\"/" pyproject.toml

    - name: Build subpackages
      run: |
        SUBDIRS=("src/fwk/env" "src/fwk/core" "src/fwk/lab")
        mkdir -p dist  # Ensure main dist exists
        for dir in "${SUBDIRS[@]}"; do
          echo "Building package in $dir"
          pushd "$dir"
          uv build
          mv dist/* ../../dist/  # Move built files to main dist
          popd
        done

    - name: Build main package
      run: |
        uv build
        mv dist/* dist/  # Ensure all packages are in the root dist/

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/