import warnings
from agi_env import AgiEnv, normalize_path
from agi_node.polars_worker import PolarsWorker
from typing import Any

logger = logging.getLogger(__name__)

class PolarsAppWorker(PolarsWorker):
    def start(self) -> Any: ...
    def work_init(self) -> Any: ...
    def pool_init(self, *args: Any, **kwargs: Any) -> Any: ...
    def work_pool(self, *args: Any, **kwargs: Any) -> Any: ...
    def work_done(self, *args: Any, **kwargs: Any) -> Any: ...
    def stop(self) -> Any: ...
